language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# Build and tag new images
script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed ismaelbernal83/udagram-api-feed:v1
  - docker tag udagram-api-user ismaelbernal83/udagram-api-user:v1
  - docker tag udagram-api-frontend ismaelbernal83/udagram-api-frontend:v1
  - docker tag udagram-reverseproxy ismaelbernal83/udagram-reverseproxy:v1

# Tasks to perform after the process is successful
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ismaelbernal83/udagram-api-feed:v1
  - docker push ismaelbernal83/udagram-api-user:v1
  - docker push ismaelbernal83/udagram-api-frontend:v1
  - docker push ismaelbernal83/udagram-reverseproxy:v1