apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy-svc
  name: reverseproxy-svc
spec:
  selector:
    app: backend-reverseproxy
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080