apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-reverseproxy
  name: backend-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-reverseproxy
  template:
    metadata:
      labels:
        app: backend-reverseproxy
    spec:
      containers:
      - image: ismaelbernal83/udagram-reverseproxy:v1
        name: reverseproxy
        ports:
        - containerPort: 8080